dist: trusty
sudo: required

language: python
python:
  - "3.6"

cache: 
    directories:
        - ~/build/SudoSharma/sentence_similarity_app/.vector_cache
        - /home/travis/.cache/pip

branches:
    only:
        - master

install: source travis/install.sh
script: 
    - python app.py &
    - sleep 5
    - curl -X GET http://127.0.0.1:5000/ -d q1="how old are you?" -d q2="howold am i?"
    - sleep 5
    - exit 
